CREATE TABLE wagers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAUL AS IDENTITY,
    FOREIGN KEY user INTEGER REFERENCES highlow_users(id) NOT NULL,
    drawn_number INTEGER NOT NULL,
    display_number INTEGER NOT NULL,
    resolution_time TIME NOT NULL
)